version: '3.8'

services:
  web:
    build: .
    #command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000 --log-level=debug
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
volumes:  # Indentação corrigida
  postgres_data: 

