version: '3.8'

services:
  web:
    container_name: api_mantis_web
    image: api_mantis_web:1.1
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000  --log-level=debug
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    container_name: api_mantis_db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    container_name: api_mantis_nginx
    build: ./nginx
    image: api_mantis_nginx:1.1
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:  # Indentação corrigida
  postgres_data: 
  static_volume:

