name: Python Application CI

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: flake8 . --extend-ignore=E501,F401,W503

    strategy:
      matrix:
        python-version: ["3.11.4"]

  # Remove a etapa de upload de cobertura, pois não é mais necessária
  # upload-coverage:  ... 
