name: Python Application CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  # Update to v4 for more flexibility
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'                 # Enable pip caching
          cache-dependency-path: '**/requirements.txt' # Cache based on requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov   # Install pytest-cov here
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: flake8 . --extend-ignore=E501,F401,W503

      #- name: Test with pytest
      #  run: |
      #    python -m venv venv     
      #    source venv/bin/activate 
      #    pip install -r requirements.txt 
      #    pytest -v tests --cov=. --cov-report=xml # Specify the test directory


    strategy:
      matrix:
        python-version: ["3.11.4"]  # Test multiple Python versions

  upload-coverage:
    name: Upload Coverage Report
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: coverage-report

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage-report/coverage.xml
